using System.Threading.Tasks;
using ArchitectureAnalyzer.Diagnostics;
using Microsoft.CodeAnalysis.Testing;
using Xunit;

namespace ArchitectureAnalyzer.Tests;

/// <summary>
/// #69: generated code that Roslyn itself recognizes (file name, &lt;auto-generated&gt; header,
/// [GeneratedCode]) is skipped by default but analyzed when generated_code=include or
/// skip_generated_code=false.
/// </summary>
public sealed class GeneratedCodeAnalysisTests
{
    private const string Contract = """
        {
          "layers": [
            { "name": "Domain", "namespaceRoots": [ "Sample.Domain" ] },
            { "name": "Application", "namespaceRoots": [ "Sample.Application" ] }
          ],
          "forbiddenDependencies": [
            { "from": "Domain", "to": "Application", "reason": "no" }
          ]
        }
        """;

    private const string Header = "// <auto-generated/>";
    private const string Attribute = "[System.CodeDom.Compiler.GeneratedCode(\"gen\", \"1.0\")] ";

    public static TheoryData<string, string, string> GeneratedKinds => new()
    {
        { "/0/Domain/D.g.cs", "// hand-written", string.Empty },
        { "/0/Domain/D.Designer.cs", "// hand-written", string.Empty },
        { "/0/Domain/D.cs", Header, string.Empty },
        { "/0/Domain/D.cs", "// hand-written", Attribute },
    };

    [Theory]
    [MemberData(nameof(GeneratedKinds))]
    public Task Default_SkipsGeneratedCode(string path, string header, string attribute)
        => RunAsync(path, header, attribute, editorConfig: null, expectDiagnostic: false);

    [Theory]
    [MemberData(nameof(GeneratedKinds))]
    public Task ExplicitSkip_SkipsGeneratedCode(string path, string header, string attribute)
        => RunAsync(
            path,
            header,
            attribute,
            """
            dotnet_diagnostic.AARC002.architecture_analyzer.generated_code = exclude
            dotnet_diagnostic.AARC002.architecture_analyzer.skip_generated_code = true
            """,
            expectDiagnostic: false);

    [Theory]
    [MemberData(nameof(GeneratedKinds))]
    public Task GeneratedCodeInclude_AnalyzesGeneratedCode(string path, string header, string attribute)
        => RunAsync(
            path,
            header,
            attribute,
            "dotnet_diagnostic.AARC002.architecture_analyzer.generated_code = include",
            expectDiagnostic: true);

    [Theory]
    [MemberData(nameof(GeneratedKinds))]
    public Task SkipGeneratedCodeFalse_AnalyzesGeneratedCode(string path, string header, string attribute)
        => RunAsync(
            path,
            header,
            attribute,
            "dotnet_diagnostic.AARC002.architecture_analyzer.skip_generated_code = false",
            expectDiagnostic: true);

    [Fact]
    public Task Default_HandWrittenFileIsStillAnalyzed()
        => RunAsync("/0/Domain/D.cs", "// hand-written", string.Empty, editorConfig: null, expectDiagnostic: true);

    private static async Task RunAsync(
        string path,
        string header,
        string attribute,
        string? editorConfig,
        bool expectDiagnostic)
    {
        var test = new ArchitectureAnalyzerTest(Contract)
        {
            TestCode = "namespace Sample.Application { public class AppService { } }",
        };

        // The source is analyzed as-is; the harness' extra "mark every file generated" pass would
        // contradict the include scenarios, which intentionally report inside generated code.
        test.TestBehaviors |= TestBehaviors.SkipGeneratedCodeCheck;
        test.TestState.Sources.Add((path, header + "\n"
            + "namespace Sample.Domain\n"
            + "{\n"
            + "    " + attribute + "public class D\n"
            + "    {\n"
            + "        public Sample.Application.AppService S { get; set; }\n"
            + "    }\n"
            + "}\n"));

        if (editorConfig is not null)
        {
            test.TestState.AnalyzerConfigFiles.Add(("/0/.editorconfig", "root = true\n\n[*.cs]\n" + editorConfig + "\n"));
        }

        if (expectDiagnostic)
        {
            test.ExpectedDiagnostics.Add(new DiagnosticResult(ArchitectureDiagnostics.ForbiddenLayerDependency)
                .WithLocation(path, 6, 35)
                .WithArguments("Sample.Domain.D", "Domain", "Sample.Application.AppService", "Application", "no"));
        }

        await test.RunAsync();
    }
}
